#!/usr/bin/env bash
# Reproducible screenshots of every WarpHold screen, over seeded demo data.
#
#   scripts/screenshots.sh                 build, seed, capture, tear down
#   scripts/screenshots.sh --plan-only     write docs/screenshots/PLAN.json only
#   scripts/screenshots.sh --only NAME     capture one screen
#   scripts/screenshots.sh --keep          leave the demo servers running
#
# The plan is the contract between this script and whatever takes the pictures:
# it names every screen, its URL and its viewport. capture.mjs follows it with
# headless Chrome; the chrome-devtools MCP driver follows the same file. See
# docs/screenshots/README.md.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=docs/screenshots
PLAN=$OUT/PLAN.json
SCRATCH=${WARPHOLD_SHOTS_DIR:-/tmp/warphold-demo}
BIN=${WARPHOLD_BIN:-$SCRATCH/warphold}
SRC=${WARPHOLD_SRC:-../warphold}

FLEET_UI=${FLEET_UI_PORT:-5411}
FLEET2_UI=${FLEET2_UI_PORT:-5412}
SOLO_UI=${SOLO_UI_PORT:-5413}
FLEET_API=${FLEET_API_PORT:-51611}
FLEET2_API=${FLEET2_API_PORT:-51612}
SOLO_API=${SOLO_API_PORT:-51613}

EMAIL=admin@example.com
PASSWORD=testpassword1
PASSPHRASE=testpassphrase

PLAN_ONLY=0 KEEP=0 ONLY=""
while [ $# -gt 0 ]; do
  case $1 in
  --plan-only) PLAN_ONLY=1 ;;
  --keep) KEEP=1 ;;
  --only) ONLY=$2; shift ;;
  *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
  shift
done

# Placeholders keep --plan-only honest: it writes a complete, readable plan
# with nothing running, and the real run overwrites these with seeded ids.
DEVICE_ID=ag_example01
DEVICE_FAILING=ag_example02
SNAPSHOT_OID=kexampleobjectid
SOLO_SOURCE=/home/user/Documents
DEMO_TARGET_PATH=$SCRATCH/hosted
SETUP_TOKEN=demo-setup-token

write_plan() {
  local fleet=http://127.0.0.1:$FLEET_UI fleet2=http://127.0.0.1:$FLEET2_UI
  # 127.0.0.2 rather than 127.0.0.1 on purpose: the UI serves the agent app on
  # loopback and the single-machine app anywhere else (src/mode.ts), so one
  # server answers as both, on two addresses.
  local solo=http://127.0.0.2:$SOLO_UI agent=http://127.0.0.1:$SOLO_UI
  local q="userName=user&host=laptop-1&path=$SOLO_SOURCE"
  # The wizard is client-side state, not routes, so steps 2-4 are step 1 plus
  # the clicks that get there. Written once and reused, so the three plan
  # entries cannot drift apart.
  local STEP1='{ "fill": ["input[autocomplete=off]", "'$SETUP_TOKEN'"] },
        { "fill": ["input[autocomplete=new-password]", "'$PASSPHRASE'"] },
        { "fill": ["input[autocomplete=new-password]", "'$PASSPHRASE'", 1] },
        { "click": ["button", "Continue"], "after": 600 }'
  local STEP2='{ "fill": ["input[type=email]", "'$EMAIL'"] },
        { "fill": ["input[autocomplete=new-password]", "'$PASSWORD'"] },
        { "click": ["button", "Continue"], "after": 600 }'
  local STEP3='{ "click": ["input[name=target-kind]", null, 1], "after": 300 },
        { "fill": ["input[autocomplete=off]", "Family disk"] },
        { "fill": ["input[autocomplete=off]", "'$DEMO_TARGET_PATH'", 1] },
        { "click": ["button", "Activate"], "after": 3000 }'
  cat >"$PLAN" <<PLANJSON
{
  "_": "Generated by scripts/screenshots.sh - do not edit by hand.",
  "viewports": {
    "1440": { "width": 1440, "height": 900, "deviceScaleFactor": 1, "mobile": false },
    "412": { "width": 412, "height": 915, "deviceScaleFactor": 1, "mobile": true }
  },
  "auth": { "fleet": { "email": "$EMAIL", "password": "$PASSWORD" } },
  "screens": [
    { "name": "fleet-login", "url": "$fleet/fleet/login",
      "caption": "Signing in to a Fleet server." },
    { "name": "fleet-overview", "url": "$fleet/fleet", "auth": "fleet",
      "caption": "The fleet dashboard: health counts, the last 24 hours and a 30-day strip per device." },
    { "name": "fleet-devices", "url": "$fleet/fleet/devices", "auth": "fleet",
      "caption": "Every enrolled device with its group, health and last good backup." },
    { "name": "fleet-device", "url": "$fleet/fleet/devices/$DEVICE_ID", "auth": "fleet",
      "caption": "One device: its sources, recent runs and the commands an admin can send it." },
    { "name": "fleet-device-failing", "url": "$fleet/fleet/devices/$DEVICE_FAILING", "auth": "fleet",
      "caption": "A device whose last backup failed, with the error it reported." },
    { "name": "fleet-groups", "url": "$fleet/fleet/groups", "auth": "fleet",
      "caption": "Groups tie a policy template to a storage target." },
    { "name": "fleet-groups-add-device", "url": "$fleet/fleet/groups", "auth": "fleet",
      "caption": "Adding a device: the group issues a one-shot token and shows the command to run.",
      "actions": [{ "click": ["button", "Download installer"], "after": 1200 }] },
    { "name": "fleet-templates", "url": "$fleet/fleet/policies", "auth": "fleet",
      "caption": "Policy templates: what to back up, how often and how long to keep it." },
    { "name": "fleet-targets", "url": "$fleet/fleet/targets", "auth": "fleet",
      "caption": "Storage targets the groups back up to." },
    { "name": "fleet-settings", "url": "$fleet/fleet/settings", "auth": "fleet",
      "caption": "Fleet settings: name, poll interval and the admin accounts." },
    { "name": "fleet-activate-1", "url": "$fleet2/fleet/activate",
      "caption": "Activation step 1: the setup token and the sealing passphrase." },
    { "name": "fleet-activate-2", "url": "$fleet2/fleet/activate",
      "caption": "Activation step 2: the first admin account.",
      "actions": [$STEP1] },
    { "name": "fleet-activate-3", "url": "$fleet2/fleet/activate",
      "caption": "Activation step 3: where the backups will live.",
      "actions": [$STEP1, $STEP2] },
    { "name": "fleet-activate-4", "url": "$fleet2/fleet/activate", "oneShot": true,
      "caption": "Activation step 4: the fleet is on, with the first enrollment command.",
      "actions": [$STEP1, $STEP2, $STEP3] },
    { "name": "solo-snapshots", "url": "$solo/snapshots",
      "caption": "The single-machine app: every source this computer backs up." },
    { "name": "solo-history", "url": "$solo/snapshots/single-source/?$q",
      "caption": "One source's snapshot history." },
    { "name": "solo-browse", "url": "$solo/snapshots/dir/$SNAPSHOT_OID",
      "caption": "Browsing inside a snapshot." },
    { "name": "solo-restore", "url": "$solo/snapshots/dir/$SNAPSHOT_OID/restore",
      "caption": "Restoring a snapshot to a directory, an archive, or a mount.",
      "actions": [{ "fill": ["input[placeholder='enter destination path']", "/home/user/Restored"] }] },
    { "name": "solo-policies", "url": "$solo/policies",
      "caption": "Policies: schedules, retention and what to leave out." },
    { "name": "solo-tasks", "url": "$solo/tasks",
      "caption": "Tasks: what the engine has been doing." },
    { "name": "solo-repository", "url": "$solo/repo",
      "caption": "The repository this machine is connected to." },
    { "name": "agent-home", "url": "$agent/agent",
      "caption": "The agent page on an enrolled device: its schedule, its runs and its 30-day strip." }
  ]
}
PLANJSON
  echo "plan: $PLAN"
}

if [ "$PLAN_ONLY" = 1 ]; then
  write_plan
  exit 0
fi

# ------------------------------------------------------------------ the build
command -v node >/dev/null || { echo "node is required" >&2; exit 1; }
if [ ! -x "$BIN" ]; then
  [ -d "$SRC" ] || { echo "no warphold source at $SRC - set WARPHOLD_SRC or WARPHOLD_BIN" >&2; exit 1; }
  echo "building the warphold server from $SRC"
  mkdir -p "$(dirname "$BIN")"
  (cd "$SRC" && CGO_ENABLED=0 go build -o "$(cd "$(dirname "$BIN")" && pwd)/$(basename "$BIN")" .)
fi
# Built into the scratch directory, never into build/: that directory is the
# committed bundle the Go module embeds, and a screenshot run must not touch it.
echo "building the UI"
npx vite build --outDir "$SCRATCH/ui" --emptyOutDir >/dev/null

PIDS=()
cleanup() {
  [ "$KEEP" = 1 ] && { echo "servers left running; state in $SCRATCH"; return; }
  for p in ${PIDS+"${PIDS[@]}"}; do kill "$p" 2>/dev/null || true; done
  if [ -f "$SCRATCH/pids" ]; then
    while read -r p; do kill "$p" 2>/dev/null || true; done <"$SCRATCH/pids"
  fi
}
trap cleanup EXIT

# ------------------------------------------------------------------ seed
rm -rf "$SCRATCH/fleet" "$SCRATCH/fleet2" "$SCRATCH/solo" "$SCRATCH/hosted" "$SCRATCH/offsite" \
  "$SCRATCH/home" "$SCRATCH/pids" "$SCRATCH/fleet2.pid" "$SCRATCH/vars.env"
FLEET_API_PORT=$FLEET_API FLEET2_API_PORT=$FLEET2_API SOLO_API_PORT=$SOLO_API \
  bash scripts/shots/seed.sh "$SCRATCH" "$BIN"
# shellcheck source=/dev/null
. "$SCRATCH/vars.env"


serve() { # serve <ui port> <api port> <hosts> [--no-fleet]
  node scripts/shots/serve.mjs --port "$1" --api "http://127.0.0.1:$2" --root "$SCRATCH/ui" --hosts "$3" "${@:4}" &
  PIDS+=($!)
}
serve "$FLEET_UI" "$FLEET_API" 127.0.0.1
serve "$FLEET2_UI" "$FLEET2_API" 127.0.0.1
serve "$SOLO_UI" "$SOLO_API" 127.0.0.1,127.0.0.2 --no-fleet
for p in $FLEET_UI $FLEET2_UI $SOLO_UI; do
  i=0
  until curl -fsS -o /dev/null "http://127.0.0.1:$p/index.html"; do
    i=$((i + 1))
    [ "$i" -gt 50 ] && { echo "ui server on $p never came up" >&2; exit 1; }
    sleep 0.2
  done
done

write_plan

# ------------------------------------------------------------------ capture
if [ -n "${WARPHOLD_SHOTS_NO_CAPTURE:-}" ]; then
  echo "capture skipped; drive $PLAN yourself (see $OUT/README.md)"
  exit 0
fi
if ! command -v chromium >/dev/null && ! command -v google-chrome >/dev/null &&
  ! command -v chromium-browser >/dev/null; then
  echo "no chromium/google-chrome on PATH - drive $PLAN with the chrome-devtools MCP instead" >&2
  exit 0
fi
node scripts/shots/capture.mjs --plan "$PLAN" --out "$OUT" ${ONLY:+--only} ${ONLY:+"$ONLY"}
# The last activation step is destructive: it activates the server it is shot
# against. One fresh server per viewport is the only way it stays repeatable.
for one in $(node -e "
  const p=require('./$PLAN');
  console.log(p.screens.filter((s)=>s.oneShot).map((s)=>s.name).join(' '));"); do
  [ -n "$ONLY" ] && [ "$ONLY" != "$one" ] && continue
  for vp in 1440 412; do
    bash scripts/shots/fleet2.sh "$SCRATCH" "$BIN" "$FLEET2_API" "$SETUP_TOKEN"
    node scripts/shots/capture.mjs --plan "$PLAN" --out "$OUT" --only "$one" --viewport "$vp"
  done
done

# ------------------------------------------------------------------ optimize
if command -v oxipng >/dev/null; then
  oxipng -q -o 4 --strip safe "$OUT"/*.png
elif command -v pngquant >/dev/null; then
  pngquant --force --skip-if-larger --strip --ext .png "$OUT"/*.png || true
fi

node scripts/shots/index.mjs --plan "$PLAN" --out "$OUT"
echo "done: $OUT"
